### ISSUE TITLE
Need push rights to update to Rivet 3.1.1

### ISSUE THREAD

**Issue by preghenella** [alisw/rivet#8]
Dear @ktf @qgp @maireiphc ,

I am ready to push to this repository to publish `Rivet 3.1.1`.
I wanted to create a new branch for that, then I will need to tag ...
Given that I have no push rights, I am unable to do that.

Can you please give me the rights for I can proceed independently?

Thanks,
Roberto

ps: I would also need the rights for the YODA repository, I got updates merged but I need to tag.

**Comment by ktf** [comment]
I think you should have already rights as you are part of @alisw/pagmc and that group is maintainer. Did you actually try?

**Comment by preghenella** [comment]
sorry, my bad.
I was trying with CERN credentials...

**Comment by preghenella** [comment]
actually @ktf ,
I managed to push to Rivet, but I cannot push to `alisw/yoda`, where I need to create a tag.
If also `alisw/yoda` part of @alisw/pagmc ?

**Comment by preghenella** [comment]
no, my bad again... don't know what went wrong before but now I pushed.

**Comment by ktf** [comment]
only @qgp was part of that one. I changed it so that @alisw/pagmc is responsible for it and dropped @qgp explicitly (as he is part of @alisw/pagmc in any case).
